export default {
  alias: 'o',
  args: '<entity>',
  description: "Open the entity's page on Wikidata website",
  options: {
    lang: true,
    verbose: true,
    clipboard: true,
    json: false,
    instance: true,
    sparqlEndpoint: false,
  },
  examples: [
    { args: 'Q44559', comment: 'Open https://www.wikidata.org/entity/Q44559 in your default browser' },
    { args: 'P123', comment: 'Open https://www.wikidata.org/entity/P123' },
    { args: 'L525', comment: 'Open https://www.wikidata.org/entity/L525' },
    { args: 'L525-F1', comment: 'Open https://www.wikidata.org/entity/L525-F1' },
    { args: 'L525-S1', comment: 'Open https://www.wikidata.org/entity/L525-S1' },
    { args: 'Q44559 --history', comment: 'Open the entity history page' },
    { args: 'Q44559 --revision 942578737', comment: 'Open the entity page at a given revision' },
    { args: 'Q44559 --wikipedia', comment: 'Open the article on Exoplanets in Wikipedia' },
    { args: 'Q44559 --wikipedia --lang pt', comment: 'Open the article on Exoplanets in the Portugese Wikipedia' },
    { args: 'Q44559 --url', comment: 'Outputs the URL without opening the browser' },
    { args: 'Q44559 L525 P123', comment: 'Open several pages at once' },
  ],
}
