#!/usr/bin/env node
// ES5 script to be able to properly detect old node versions

var red = require('chalk').red

var parts = process.version
  .slice(1)
  .split('.')
  .map(num => parseInt(num))

var major = parts[0]
var minor = parts[1]
var patch = parts[2]

if ((major === 6 && minor < 4) || major < 6) {
  console.error(red('INVALID NODE VERSION'), '(' + process.version + ')')
  console.error('Please update to a Node version above v6.4')
  process.exit(1)
} else {
  process.exit(0)
}
