#!/usr/bin/env bash

set -eu

version=$(node -p "require('./package.json').version")

docker build -t wikibase-cli .
docker tag wikibase-cli "maxlath/wikibase-cli:${version}"
docker push "maxlath/wikibase-cli:${version}"
docker tag wikibase-cli maxlath/wikibase-cli:latest
docker push maxlath/wikibase-cli:latest
